//
//  TestUtils.h
//  ImproveUnitTests
//
//  Created by Vladimir on 2/2/20.
//  Copyright © 2020 Mind Blown Apps, LLC. All rights reserved.
//

// Helper utilities for testing.

#include <math.h>
#import <Foundation/Foundation.h>
#import "IMPLogging.h"

#ifndef TestUtils_h
#define TestUtils_h

NS_INLINE BOOL __attribute__((overloadable)) isEqualRough(double fl1, double fl2, double precision) {
    if (fl1 == fl2) {
        return YES;
    } if (fl1 == 0. || fl2 == 0.) {
        return ABS(fl1 - fl2) < precision;
    } else if (fl1 > fl2) {
        return (ABS(fl1 / fl2) - 1.) < precision;
    } else {
        return (ABS(fl2 / fl1) - 1.) < precision;
    }
}

NS_INLINE BOOL __attribute__((overloadable)) isEqualRough(double fl1, double fl2) {
    const double precision = 0.001;
    return isEqualRough(fl1, fl2, precision);
}

NS_INLINE BOOL __attribute__((overloadable)) isEqualRough(int count, double *buf1, double *buf2) {
    for (int i = 0; i < count; i++) {
        if (!isEqualRough(*(buf1 + i), *(buf2 + i))) {
            return NO;
        }
    }
    return YES;
}


@interface TestUtils: NSObject

/**
 Test resources can be found in this bundle.
 As well as any other bundle derived from a class from the test target.
 */
+ (NSBundle *)bundle;

/// Contains random "trials" and "predictions" arrays generated by XGBoost. This data is stored in "trials.json".
+ (NSDictionary *)defaultTrialsAndPredictions;

/// Trials from "trials.json" which where randomly generated.
+ (NSArray *)defaultTrials;

/// Predictions from "trials.json" which are supposed to be generated by XGBoost.
+ (NSArray *)defaultPredictions;

/// Namespace which was used to generate "trials.json"
+ (NSString *)defaultNamespace;

+ (NSString *)randomStringWithLength:(NSInteger)length;

+ (NSString *)randomStringWithMinLength:(NSInteger)minLength maxLength:(NSInteger)maxLength;

@end

#endif /* TestUtils_h */
