# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'IMPSwiftExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IMPSwiftExample
  pod 'Improve', :path => '../'

  target 'IMPSwiftExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IMPSwiftExampleUITests' do
    # Pods for testing
  end

end
